# Generated by Django 3.1.6 on 2021-03-16 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_price', models.PositiveIntegerField()),
                ('flat_size', models.PositiveIntegerField()),
                ('flat_rooms', models.PositiveIntegerField()),
                ('flat_for', models.CharField(max_length=2)),
                ('flat_address', models.CharField(max_length=200)),
                ('flat_pincode', models.CharField(max_length=6)),
                ('flat_city', models.CharField(max_length=100)),
                ('flat_state', models.CharField(max_length=100)),
                ('is_verified_flat', models.BooleanField(default=False)),
                ('photo1', models.ImageField(upload_to='flat_image')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='flat_image')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='flat_image')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='flat_image')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='flat_image')),
                ('flat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
