# Generated by Django 3.1.6 on 2021-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_for',
            field=models.CharField(max_length=10),
        ),
    ]
