# Generated by Django 3.1.6 on 2021-05-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatamenities',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='HOME.flat'),
        ),
        migrations.AlterField(
            model_name='flatimages',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HOME.flat'),
        ),
    ]
