# Generated by Django 3.1.6 on 2021-04-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_auto_20210407_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='flat_locality',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
