# Generated by Django 3.1.6 on 2021-04-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_flat_flat_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='flat_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
